import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/home_screen.dart';
import 'screens/program_listing_screen.dart';
import 'screens/program_details_screen.dart';
import 'screens/my_programs_screen.dart';
import 'screens/placeholder_screen.dart';
import 'screens/main_navigation_screen.dart';
import 'screens/activity_feed_screen.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}


class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Excellerate Prototype',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(
          seedColor: Colors.green,
          secondary: Colors.orange,
        ),
        useMaterial3: true,
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.green,
          foregroundColor: Colors.white,
          elevation: 0,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: Colors.green,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
          ),
        ),
        // Using Material 3 CardTheme for modern design
        cardTheme: CardThemeData(
          elevation: 2.0,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
          clipBehavior: Clip.antiAlias,
        ),
      ),
      initialRoute: '/login',
      routes: {
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/home': (context) => const MainNavigationScreen(),
        '/program_listing': (context) => const ProgramListingScreen(),
        '/program_details': (context) => const ProgramDetailsScreen(),
        '/my_programs': (context) => const MyProgramsScreen(),
        '/assignments': (context) => PlaceholderScreen(
              title: 'Assignments',
              icon: Icons.assignment_outlined,
              message: 'Track your progress and complete assignments for your enrolled programs.',
              actionLabel: 'View Programs',
              onActionPressed: () => Navigator.pushNamed(context, '/my_programs'),
            ),
        '/community': (context) => const PlaceholderScreen(
              title: 'Community',
              icon: Icons.people_outline,
              message: 'Connect with fellow learners, share experiences, and participate in discussions.',
            ),
        '/progress': (context) => const PlaceholderScreen(
              title: 'Progress',
              icon: Icons.analytics_outlined,
              message: 'Track your learning journey and monitor your achievements.',
            ),
          '/activity_feed': (context) => const ActivityFeedScreen(),
        '/settings': (context) => const PlaceholderScreen(
              title: 'Settings',
              icon: Icons.settings_outlined,
              message: 'Customize your app preferences and manage your account settings.',
            ),
      },
    );
  }
}
